'use strict';
const $=id=>document.getElementById(id), C=window.AppCore;
const monetaryIds=['averagePrice','minimumNet','autCleaning','autFixed','autMaintenance','agencyCleaning','agencyFixed','agencyExtra','agencyMaintenance'];
const numericIds=['rooms','days','averagePrice','occupancy','otaCommission','agencyCommission','minimumNet','desiredIncrease','taxRate','autCleaning','autFixed','autMaintenance','agencyCleaning','agencyFixed','agencyExtra','agencyMaintenance'];
const checkIds=['includeTaxes','autIncludeCleaning','autIncludeFixed','autIncludeMaintenance','agencyIncludeCleaning','agencyIncludeFixed','agencyIncludeExtra','agencyIncludeMaintenance'];
const defaults={rooms:5,days:30,averagePrice:70,occupancy:60,otaCommission:23.5,agencyCommission:20,agencyCommissionBase:'gross',minimumNet:2000,desiredIncrease:10,taxRate:0,includeTaxes:false,autCleaning:0,autFixed:0,autMaintenance:0,agencyCleaning:0,agencyFixed:0,agencyExtra:0,agencyMaintenance:0,autIncludeCleaning:false,autIncludeFixed:false,autIncludeMaintenance:false,agencyIncludeCleaning:false,agencyIncludeFixed:false,agencyIncludeExtra:false,agencyIncludeMaintenance:false,language:'it'};
const STORAGE='affittacamere-current-v7',SCENARIOS='affittacamere-scenarios-v2';
const money=v=>Number.isFinite(v)?new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(v):'Non calcolabile';
const num=(v,d=2)=>Number.isFinite(v)?new Intl.NumberFormat('it-IT',{maximumFractionDigits:d}).format(v):'—';
const pct=v=>Number.isFinite(v)?`${num(v,2)}%`:'—';
function read(){const v={};numericIds.forEach(id=>v[id]=C.parseLocaleNumber($(id).value,{monetary:monetaryIds.includes(id)}));checkIds.forEach(id=>v[id]=$(id).checked);v.agencyCommissionBase=$('agencyCommissionBase').value;v.language=$('language').value;return v}
function apply(v){numericIds.forEach(id=>$(id).value=String(v[id]??defaults[id]).replace('.',','));checkIds.forEach(id=>$(id).checked=!!v[id]);$('agencyCommissionBase').value=v.agencyCommissionBase||'gross';$('language').value=v.language||'it';update()}
function save(v){try{localStorage.setItem(STORAGE,JSON.stringify(v))}catch{}}
function set(id,val){const e=$(id);if(e)e.textContent=val}
function resultLabel(v){return C.allCostsEnabled(v)?'Netto stimato':(v.includeTaxes||C.modeCosts(v,'aut')>0||C.modeCosts(v,'agency')>0?'Margine dopo i costi selezionati':'Residuo dopo commissioni')}
function markLoss(panelId,value,labelId){const panel=$(panelId),loss=$(panelId==='autPanel'?'autLoss':'agencyLoss'),valueEl=$(labelId);panel.classList.toggle('bad-panel',value<0);valueEl.classList.toggle('negative',value<0);loss.style.display=value<0?'block':'none';loss.textContent=value<0?'Scenario in perdita':''}
function renderRequired(v,mode){const x=C.requiredOccupancy(v,mode),s=mode==='aut'?'Aut':'Agency',panel=$(mode==='aut'?'requiredAutPanel':'requiredAgencyPanel');if(!x){set('requiredOccupancy'+s,'Non calcolabile');set('requiredDetails'+s,'Controlla i valori e le percentuali.');panel.className='result-panel bad-panel';return}set('requiredOccupancy'+s,pct(x.occupancy));set('requiredDetails'+s,`${num(x.nights)} notti, ${num(x.roomsPerDay)} camere al giorno, lordo ${money(x.gross)}.`);panel.className='result-panel '+(x.occupancy>100?'bad-panel':v.occupancy>=x.occupancy?'good-panel':'');}
function assumptions(v){const base=v.agencyCommissionBase==='gross'?'sul fatturato lordo':'sul fatturato dopo OTA';const lines=[`Commissione OTA applicata sul fatturato lordo: ${pct(v.otaCommission)}.`,`Commissione agenzia calcolata ${base}.`,`Imposte ${v.includeTaxes?`incluse al ${pct(v.taxRate)}`:'escluse'}.`,`Costi autonoma inclusi: ${money(C.modeCosts(v,'aut'))}.`,`Costi agenzia inclusi: ${money(C.modeCosts(v,'agency'))}.`,`Valori annuali calcolati moltiplicando il risultato mensile per 12.`];$('assumptions').innerHTML=lines.map(x=>`<li>${x}</li>`).join('')}
function update(){const v=read(),errors=C.validate(v);$('errorBox').style.display=errors.length?'block':'none';$('errorBox').innerHTML=errors.map(e=>`<div>${e}</div>`).join('');save(v);if(errors.length)return false;const r=C.calculate(v),label=resultLabel(v);set('resultNote',C.allCostsEnabled(v)?'Tutti i costi selezionati e le imposte stimate sono inclusi: il risultato è un netto stimato.':'Le imposte sul reddito e gli altri costi non selezionati non sono inclusi nel risultato.');set('availableNights',num(r.available));set('soldNights',num(r.sold));set('averageOccupiedRooms',num(r.avgOccupied));set('grossRevenue',money(r.gross));set('autResultLabel',label);set('agencyResultLabel',label);set('autNet',money(r.autNet));set('agencyNet',money(r.agencyNet));set('autOtaCost',money(r.otaCost));set('agencyOtaCost',money(r.otaCost));set('agencyCost',`${money(r.agencyCost)} (${v.agencyCommissionBase==='gross'?'sul lordo':'dopo OTA'})`);set('autCosts',money(r.autCosts));set('agencyCosts',money(r.agencyCosts));set('autAnnual',money(r.autAnnual));set('agencyAnnual',money(r.agencyAnnual));set('breakEvenGross',money(r.breakEvenGross));set('breakEvenEuro',money(r.breakEvenEuro));set('breakEvenPct',pct(r.breakEvenPct));set('higherGross',money(r.higherGross));set('goalGrossAut',money(r.goalGrossAut));set('goalGrossAgency',money(r.goalGrossAgency));
const diff=r.autNet-r.agencyNet;set('decisionMonthlyDifference',money(diff));set('decisionBreakEven',money(r.breakEvenGross));set('decisionHigher',money(r.higherGross));set('decisionMinimum',`Aut. ${money(r.goalGrossAut)} · Ag. ${money(r.goalGrossAgency)}`);$('decisionSummary').innerHTML=`Con lo stesso fatturato lordo, la gestione <strong>${diff>=0?'autonoma':'tramite agenzia'}</strong> lascia <strong>${money(Math.abs(diff))}</strong> in più al mese. L’agenzia diventa equivalente se produce almeno <strong>${money(r.breakEvenGross)}</strong> lordi. Per ottenere il ${pct(v.desiredIncrease)} in più deve produrre <strong>${money(r.higherGross)}</strong> lordi. L’obiettivo minimo di ${money(v.minimumNet)} ${r.autNet>=v.minimumNet?'è':'non è'} raggiunto in autonomia e ${r.agencyNet>=v.minimumNet?'è':'non è'} raggiunto con agenzia.`;
markLoss('autPanel',r.autNet,'autNet');markLoss('agencyPanel',r.agencyNet,'agencyNet');renderRequired(v,'aut');renderRequired(v,'agency');assumptions(v);window.lastCalculation={v,r};return true}
let timer;function schedule(e){clearTimeout(timer);timer=setTimeout(()=>{update();notify(e?.target?.id)},120)}
const fieldNames={rooms:'Numero camere',days:'Giorni',averagePrice:'Prezzo medio',occupancy:'Occupazione',otaCommission:'Commissione OTA',agencyCommission:'Commissione agenzia',agencyCommissionBase:'Base commissione agenzia',minimumNet:'Obiettivo mensile',desiredIncrease:'Guadagno desiderato',includeTaxes:'Imposte'};
function notify(id){if(!id)return;const t=$('changeToast');t.innerHTML=`<strong>Aggiornato: ${fieldNames[id]||'costi dello scenario'}</strong><br><small>Riepilogo, risultati e formule inverse sono stati ricalcolati.</small>`;t.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>t.classList.remove('show'),2500);document.querySelectorAll('.decision,.result-panel').forEach(x=>{x.classList.remove('updated');void x.offsetWidth;x.classList.add('updated')})}
function costsText(v,mode){const parts=[],p=mode==='aut'?'aut':'agency';if(v[p+'IncludeCleaning'])parts.push(`pulizie ${money(v[p+'Cleaning'])}`);if(v[p+'IncludeFixed'])parts.push(`costi fissi ${money(v[p+'Fixed'])}`);if(v[p+'IncludeMaintenance'])parts.push(`manutenzione/altri costi ${money(v[p+'Maintenance'])}`);if(mode==='agency'&&v.agencyIncludeExtra)parts.push(`extra agenzia ${money(v.agencyExtra)}`);return parts.length?parts.join(', '):'nessun costo aggiuntivo selezionato'}
function italian(v,r){const diff=r.autNet-r.agencyNet,better=diff>=0?'gestione autonoma':'gestione tramite agenzia';return `La simulazione considera ${num(v.rooms)} camere e ${num(v.days)} giorni nel mese, per un totale di ${num(r.available)} notti disponibili. Con un’occupazione media del ${pct(v.occupancy)} vengono vendute circa ${num(r.sold)} notti, equivalenti a ${num(r.avgOccupied)} camere occupate mediamente ogni giorno. Il prezzo medio è ${money(v.averagePrice)} e il fatturato lordo mensile stimato è ${money(r.gross)}.\n\nLa commissione media Booking/OTA è del ${pct(v.otaCommission)}, pari a ${money(r.otaCost)}. Questa percentuale rappresenta una media complessiva di commissioni, costi di transazione e IVA sui servizi OTA.\n\nNella gestione autonoma sono inclusi: ${costsText(v,'aut')}. Il risultato mensile è ${money(r.autNet)} e quello annuale, calcolato moltiplicando per 12, è ${money(r.autAnnual)}.\n\nNella gestione tramite agenzia, la commissione del ${pct(v.agencyCommission)} è calcolata ${v.agencyCommissionBase==='gross'?'sul fatturato lordo':'sul fatturato dopo le commissioni OTA'} ed è pari a ${money(r.agencyCost)}. Sono inoltre inclusi: ${costsText(v,'agency')}. Il risultato mensile è ${money(r.agencyNet)} e quello annuale è ${money(r.agencyAnnual)}.\n\nCon lo stesso fatturato lordo, la differenza è di ${money(Math.abs(diff))} al mese e ${money(Math.abs(diff)*12)} all’anno a favore della ${better}. Per lasciare lo stesso risultato della gestione autonoma, l’agenzia deve produrre almeno ${money(r.breakEvenGross)} lordi: ${money(r.breakEvenEuro)} in più, cioè il ${pct(r.breakEvenPct)}. Per ottenere un guadagno superiore del ${pct(v.desiredIncrease)}, deve produrre circa ${money(r.higherGross)} lordi.\n\nL’obiettivo minimo mensile di ${money(v.minimumNet)} ${r.autNet>=v.minimumNet?'viene':'non viene'} raggiunto con la gestione autonoma e ${r.agencyNet>=v.minimumNet?'viene':'non viene'} raggiunto con l’agenzia.\n\nConclusione: a parità di fatturato, in questa simulazione risulta più favorevole la ${better}. L’agenzia può diventare equivalente o migliore solo se aumenta il fatturato fino ai livelli indicati. ${C.allCostsEnabled(v)?'Il risultato include tutti i costi selezionati e le imposte stimate.':'Le imposte e gli altri costi non selezionati non sono inclusi.'}`}
function bangla(v,r){const diff=r.autNet-r.agencyNet,better=diff>=0?'নিজে পরিচালনা':'এজেন্সির মাধ্যমে পরিচালনা';return `এই হিসাবটি ${num(v.rooms)}টি কক্ষ এবং মাসের ${num(v.days)} দিনের ওপর ভিত্তি করে করা হয়েছে। মোট ${num(r.available)}টি রাত বিক্রির জন্য পাওয়া যায়। গড় দখল হার ${pct(v.occupancy)} হলে প্রায় ${num(r.sold)}টি রাত বিক্রি হয়, অর্থাৎ প্রতিদিন গড়ে ${num(r.avgOccupied)}টি কক্ষ ভাড়া থাকে। প্রতি রাতের গড় মূল্য ${money(v.averagePrice)} এবং আনুমানিক মাসিক মোট আয় ${money(r.gross)}।\n\nBooking/OTA-এর গড় কমিশন ${pct(v.otaCommission)}, অর্থাৎ ${money(r.otaCost)}। এই শতাংশের মধ্যে গড় কমিশন, লেনদেন খরচ এবং OTA পরিষেবার ভ্যাট ধরা হয়েছে।\n\nনিজে পরিচালনার ক্ষেত্রে অন্তর্ভুক্ত খরচ: ${costsText(v,'aut')}। মাসিক ফলাফল ${money(r.autNet)} এবং ১২ মাস ধরে বার্ষিক ফলাফল ${money(r.autAnnual)}।\n\nএজেন্সির কমিশন ${pct(v.agencyCommission)} এবং এটি ${v.agencyCommissionBase==='gross'?'মোট আয়ের ওপর':'OTA কমিশন বাদ দেওয়ার পরের আয়ের ওপর'} হিসাব করা হয়েছে। কমিশনের পরিমাণ ${money(r.agencyCost)}। এজেন্সির ক্ষেত্রে অন্তর্ভুক্ত খরচ: ${costsText(v,'agency')}। মাসিক ফলাফল ${money(r.agencyNet)} এবং বার্ষিক ফলাফল ${money(r.agencyAnnual)}।\n\nএকই মোট আয়ে দুই ব্যবস্থার মাসিক পার্থক্য ${money(Math.abs(diff))} এবং বার্ষিক পার্থক্য ${money(Math.abs(diff)*12)}; এই হিসাবে ${better} বেশি সুবিধাজনক। নিজে পরিচালনার সমান ফল পেতে এজেন্সিকে অন্তত ${money(r.breakEvenGross)} মোট আয় করতে হবে, অর্থাৎ ${money(r.breakEvenEuro)} বা ${pct(r.breakEvenPct)} বেশি। ${pct(v.desiredIncrease)} বেশি লাভ পেতে এজেন্সির প্রয়োজন প্রায় ${money(r.higherGross)} মোট আয়।\n\nমাসিক ন্যূনতম লক্ষ্য ${money(v.minimumNet)} নিজে পরিচালনায় ${r.autNet>=v.minimumNet?'পূরণ হয়েছে':'পূরণ হয়নি'} এবং এজেন্সির মাধ্যমে ${r.agencyNet>=v.minimumNet?'পূরণ হয়েছে':'পূরণ হয়নি'}।\n\nসহজ সিদ্ধান্ত: একই মোট আয়ে ${better} বেশি অর্থ রেখে দেয়। এজেন্সি তখনই সমান বা ভালো হবে, যখন উপরে দেখানো পরিমাণ পর্যন্ত মোট আয় বাড়াতে পারবে। ${C.allCostsEnabled(v)?'নির্বাচিত সব খরচ ও আনুমানিক কর ফলাফলে অন্তর্ভুক্ত।':'নির্বাচন না করা কর ও অন্যান্য খরচ ফলাফলে অন্তর্ভুক্ত নয়।'}`}
function generate(){if(!update())return;const {v,r}=window.lastCalculation;$('generatedMessage').value=v.language==='bn'?bangla(v,r):italian(v,r)}
async function copy(){if(!$('generatedMessage').value)generate();try{await navigator.clipboard.writeText($('generatedMessage').value)}catch{$('generatedMessage').select();document.execCommand('copy')}$('copyConfirmation').textContent='Copiato';setTimeout(()=>$('copyConfirmation').textContent='',1500)}
function scenarios(){try{return JSON.parse(localStorage.getItem(SCENARIOS)||'[]')}catch{return[]}}function renderScenarios(){const list=scenarios();$('scenarioList').innerHTML=list.length?list.map(s=>`<div class="scenario-item"><span><strong>${s.name}</strong><br><small>${new Date(s.date).toLocaleString('it-IT')}</small></span><span><button data-load="${s.id}" class="btn-secondary">Carica</button> <button data-delete="${s.id}" class="btn-secondary">Elimina</button></span></div>`).join(''):'Nessuno scenario salvato.'}$('scenarioList').addEventListener('click',e=>{const l=e.target.dataset.load,d=e.target.dataset.delete,list=scenarios();if(l)apply({...defaults,...list.find(x=>x.id===l).values});if(d){localStorage.setItem(SCENARIOS,JSON.stringify(list.filter(x=>x.id!==d)));renderScenarios()}})
function saveScenario(){const name=$('scenarioName').value.trim();if(!name){$('errorBox').style.display='block';$('errorBox').textContent='Inserisci un nome per lo scenario.';return}const list=scenarios();list.unshift({id:String(Date.now()),name,date:new Date().toISOString(),values:read()});localStorage.setItem(SCENARIOS,JSON.stringify(list));$('scenarioName').value='';renderScenarios()}
function weighted(){const ids=['bookingShare','bookingRate','otherShare','otherRate','directShare','directRate'],v={};ids.forEach(id=>v[id]=C.parseLocaleNumber($(id).value,{monetary:false}));const total=v.bookingShare+v.otherShare+v.directShare;if(!ids.every(id=>Number.isFinite(v[id]))||Math.abs(total-100)>.01){set('weightedOtaResult',' Le quote devono sommare 100%.');return}const avg=(v.bookingShare*v.bookingRate+v.otherShare*v.otherRate+v.directShare*v.directRate)/100;$('otaCommission').value=String(avg).replace('.',',');set('weightedOtaResult',` Media applicata: ${pct(avg)}`);update()}
function reset(){localStorage.removeItem(STORAGE);apply(defaults)}
[...numericIds,...checkIds,'agencyCommissionBase'].forEach(id=>{const e=$(id);e.addEventListener('input',schedule);e.addEventListener('change',schedule)});$('calculateBtn').onclick=()=>{update();notify('manual')};$('resetBtn').onclick=reset;$('generateMessageBtn').onclick=generate;$('copyMessageBtn').onclick=copy;$('saveScenarioBtn').onclick=saveScenario;$('applyWeightedOta').onclick=weighted;
try{apply({...defaults,...JSON.parse(localStorage.getItem(STORAGE)||'{}')})}catch{apply(defaults)}renderScenarios();